import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Script from "next/script";
import Footer from "@/components/layout/Footer";
import CreateModal from "@/components/portal/CreateModal";
import CreateAlert from "@/components/portal/CreateAlert";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ReactQueryProvider>
      <html lang="ko">
        <body className={openSans.className}>
          <div id="modal" />
          <div id="back_drop" />
          <div id="alert" />
          <main>{children}</main>
          <Footer />
          <ReactQueryDevtools initialIsOpen={false} />
          <CreateModal />
          <CreateAlert />
          <Script
            src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_API_KEY}&libraries=services,clusterer&autoload=false`}
            strategy="beforeInteractive"
          />
          <Script src="https://cdn.iamport.kr/v1/iamport.js" />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
